apiVersion: apps/v1
kind: Deployment
metadata:
  name: utlity-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: utlity-api
  template:
    metadata:
      labels:
        app: utlity-api
    spec:
      containers:
      - name: utlity-api
        image: webapp:1
        # for local development against minikube registry
        #imagePullPolicy: Never        
        ports:
        - containerPort: 8080
        env:
        - name: APP_REGION
          value: "us-south"
        - name: APP_RUNTIME
          value: "dw-rocs-cluster"
        - name: LOG_LEVEL
          value: "debug"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"      
---
apiVersion: v1
kind: Service
metadata:
  name: utility-api-service
  labels:
    app: utility-api-service
spec:
  type: ClusterIP
  ports:
    # the port that this service should serve on
    - port: 80
      targetPort: 8080
  # label keys and values that must match in order to receive traffic for this service
  selector:
    app: utlity-api
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: utility-api-ingress
spec:
  tls:
  - hosts:
    - utility-api.dev.eyebeemdemos.com
    secretName: eyebeemdemos-secret-tls
  rules:
  - host: utility-api.dev.eyebeemdemos.com
    http:
      paths:
      - path: /
        backend:
          serviceName: utility-api-service
          servicePort: 80